import { describe, expect, it } from 'vitest';
import {
  discussionWatermark,
  reviewPublicationPayload,
  reviewableDiffLines,
  validateReviewCommentLocations,
  type DiscussionEntry,
  type GithubDiscussionNode,
} from './github.js';

function entry(id: string, login: string, updatedAt: string, authorAssociation = 'NONE'): DiscussionEntry {
  return { id, fullDatabaseId: id, updatedAt, author: { login }, authorAssociation };
}

function node(entries: DiscussionEntry[]): GithubDiscussionNode {
  return {
    number: 1,
    author: { login: 'pull-author' },
    comments: { nodes: entries },
    reviews: { nodes: [] },
    reviewThreads: { nodes: [] },
  };
}

describe('discussionWatermark', () => {
  it('tracks PR-author and collaborator feedback while excluding the authenticated reviewer', () => {
    const watermark = discussionWatermark(node([
      entry('10', 'cb1kenobi', '2026-09-01T10:00:00Z', 'OWNER'),
      entry('11', 'random-reader', '2026-09-01T11:00:00Z'),
      entry('12', 'pull-author', '2026-09-01T12:00:00Z'),
      entry('13', 'maintainer', '2026-09-01T13:00:00Z', 'MEMBER'),
    ]), 'cb1kenobi');
    expect(watermark).toContain('2026-09-01T13:00:00Z');
    expect(watermark).toContain('13');
  });

  it('is unchanged by self-authored or untrusted discussion', () => {
    expect(discussionWatermark(node([
      entry('1', 'cb1kenobi', '2026-09-01T10:00:00Z', 'OWNER'),
      entry('2', 'random-reader', '2026-09-01T11:00:00Z'),
    ]), 'cb1kenobi')).toBe('');
  });
});

describe('reviewableDiffLines', () => {
  const diff = `diff --git a/src/file.ts b/src/file.ts
--- a/src/file.ts
+++ b/src/file.ts
@@ -10,3 +10,3 @@
 context
-removed
+added
 context`;

  it('distinguishes deleted lines from added and context lines', () => {
    const lines = reviewableDiffLines(diff);
    expect(lines.has(['src/file.ts', 'RIGHT', '10'].join('\0'))).toBe(true);
    expect(lines.has(['src/file.ts', 'LEFT', '11'].join('\0'))).toBe(true);
    expect(lines.has(['src/file.ts', 'RIGHT', '11'].join('\0'))).toBe(true);
    expect(lines.has(['src/file.ts', 'RIGHT', '12'].join('\0'))).toBe(true);
  });

  it('rejects comments outside the supplied diff', () => {
    expect(() => validateReviewCommentLocations(diff, [
      { path: 'src/file.ts', line: 11, side: 'RIGHT', body: 'Confirmed issue.' },
    ])).not.toThrow();
    expect(() => validateReviewCommentLocations(diff, [
      { path: 'other.ts', line: 1, side: 'RIGHT', body: 'Not in diff.' },
    ])).toThrow('does not point');
  });
});

describe('reviewPublicationPayload', () => {
  it('signs inline findings without adding a redundant review summary', () => {
    const payload = reviewPublicationPayload('1234567890', 'One issue.', [
      { path: 'file.ts', line: 2, side: 'RIGHT', body: '**High: broken invariant**\n\nFailure mode.' },
    ]);
    expect(payload).not.toHaveProperty('body');
    expect(payload.comments[0]?.body).toContain('Generated by Barber AI');
  });

  it('refuses to create an empty review payload', () => {
    expect(() => reviewPublicationPayload('1234567890', 'The change is safe.', []))
      .toThrow('Refusing to publish an empty pull request review');
  });
});
