import type { ReviewBundle, ReviewCommentDraft } from './github.js';

interface ExistingInlineComment {
  path?: unknown;
  line?: unknown;
  side?: unknown;
  original_line?: unknown;
  original_side?: unknown;
  body?: unknown;
}

function normalizedCommentText(body: string): string {
  return body
    .replace(/\n?—\s*\n?_Generated by Barber AI_\s*$/i, '')
    .replace(/\n?—\s*\n?(?:[^\r\n]{1,80}\s+)?reviewed\s+[A-Za-z0-9._-]{7,64}\s*$/i, '')
    .replace(/[`*_#>]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

function normalizedCommentTitle(body: string): string {
  return normalizedCommentText(body.split(/\r?\n/).find((line) => line.trim()) || '');
}

/** Remove findings that are already present in the PR discussion or repeated in one result. */
export function newReviewComments(bundle: Pick<ReviewBundle, 'inlineComments'>, comments: ReviewCommentDraft[]): ReviewCommentDraft[] {
  const existing = bundle.inlineComments.flatMap((value) => {
    if (!value || typeof value !== 'object') return [];
    const comment = value as ExistingInlineComment;
    if (typeof comment.path !== 'string' || typeof comment.body !== 'string') return [];
    const line = Number.isInteger(comment.line) ? comment.line : comment.original_line;
    const side = comment.side === 'LEFT' || comment.side === 'RIGHT' ? comment.side : comment.original_side;
    if (!Number.isInteger(line) || (side !== 'LEFT' && side !== 'RIGHT')) return [];
    return [{
      path: comment.path,
      line: line as number,
      side,
      text: normalizedCommentText(comment.body),
      title: normalizedCommentTitle(comment.body),
    }];
  });
  const accepted: Array<ReviewCommentDraft & { text: string; title: string }> = [];
  for (const comment of comments) {
    const text = normalizedCommentText(comment.body);
    const title = normalizedCommentTitle(comment.body);
    const duplicate = [...existing, ...accepted].some((candidate) => (
      candidate.path === comment.path
      && candidate.line === comment.line
      && candidate.side === comment.side
      && (candidate.text === text || (Boolean(candidate.title) && candidate.title === title))
    ));
    if (!duplicate) accepted.push({ ...comment, text, title });
  }
  return accepted.map(({ text: _text, title: _title, ...comment }) => comment);
}
